### ISSUE TITLE
dockerhub有个容器 clipboardsync 怎么运行了无法连接呢 

### ISSUE THREAD

**Issue by a872675986** [clipboard-sync/socket-server#2]
dockerhub有个容器 clipboardsync 安装完把80端口改成别的了 网页能访问 提示WebSocket Protocol Error: Unable to parse WebSocket key. 但是客户端无法连接是什么问题呢大佬 难道是我安装错误了吗

**Comment by mscststs** [comment]
看起来这个docker与这个项目无关。

后续会考虑打一个docker发布到dockerhub上

**Comment by a872675986** [comment]
> 看起这个docker与这个项目无关。
> 
> 后续会考虑打一个docker发布到dockerhub上
期待 目前用命令拉取 在nas上没反应 o(〃'▽'〃)o  有映像就方便很多了

**Comment by mscststs** [comment]
> > 看起这个docker与这个项目无关。
> > 后续会考虑打一个docker发布到dockerhub上
> > 期待 目前用命令拉取 在nas上没反应 o(〃'▽'〃)o  有映像就方便很多了

https://hub.docker.com/r/mscststs/clipboard-sync-socket-server/tags

**Comment by a872675986** [comment]
感谢感谢 经过测试正常使用
